# Generated by Django 3.2.5 on 2021-08-08 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True)),
                ('sent_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
